

services:
  lab1:
    build:               
      context: ./Lab1
      dockerfile: Dockerfile
    container_name: lab1_container
    image: lab1_image
    volumes:
      - ./Lab1:/app
    tty: true
    stdin_open: true

  homework1:
    build:              
      context: ./homework1
      dockerfile: Dockerfile.hw
    container_name: home_work1
    image: home_work_image
    volumes:
      - ./homework1:/app
    tty: true
    stdin_open: true

  Lab2:
    build:
      context: ./Lab2
      Dockerfile: Dockerfile
    container_name: Lab2_work
    image: Lab2_image
    volumes:
      - ./Lab2:/app
    tty: true
    stdin_open: true

  Lab3:
    build:
      context: ./Lab3
      Dockerfile: Dockerfile
    container_name: Lab3_work
    image: Lab3_image
    volumes:
      - ./Lab3:/app
    tty: true
    stdin_open: true