version: '3.8'

services:
  lab1:
    builds:
      context: ./lab1
    container_name: lab1_container
    image: lab1_image
    command: ./Lab1
    volumes:
      - ./lab1:/app
  homework1:
    builds:
      context: ./magic
    container_name: home_work1
    image: home_work_image
    command: ./magic
    volumes:
      -./homework1:/app


    
