

services:
  lab1:
    build:               
      context: ./Lab1
      dockerfile: Dockerfile
    container_name: lab1_container
    image: lab1_image
    volumes:
      - ./Lab1:/app
    tty: true
    stdin_open: true

  homework1:
    build:              
      context: ./homework1
      dockerfile: Dockerfile.hw
    container_name: home_work1
    image: home_work_image
    volumes:
      - ./homework1:/app
    tty: true
    stdin_open: true
